# Generated by Django 4.2.7 on 2025-12-12 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("course", "0002_remove_question_mcq_correct_answer_index_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("instructions", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(default=60, help_text="Duration in minutes"),
                ),
                ("total_marks", models.IntegerField(default=100)),
                ("passing_marks", models.IntegerField(default=60)),
                ("enable_proctoring", models.BooleanField(default=False)),
                (
                    "total_attempts",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of attempts made"
                    ),
                ),
                (
                    "question_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of question UUIDs from the Question model",
                    ),
                ),
                (
                    "publish_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("organizer", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("company", "Company"), ("college", "College")],
                        default="company",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("ongoing", "Ongoing"),
                            ("past", "Past"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("prize", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Course this assessment belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_assessments",
                        to="course.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific topic within the course (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_assessments",
                        to="course.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="JobTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("instructions", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(default=60, help_text="Duration in minutes"),
                ),
                ("total_marks", models.IntegerField(default=100)),
                ("passing_marks", models.IntegerField(default=60)),
                ("enable_proctoring", models.BooleanField(default=False)),
                (
                    "total_attempts",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of attempts made"
                    ),
                ),
                (
                    "question_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of question UUIDs from the Question model",
                    ),
                ),
                (
                    "publish_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("position_title", models.CharField(max_length=255)),
                ("start_datetime", models.DateTimeField(blank=True, null=True)),
                ("end_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Course this assessment belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_assessments",
                        to="course.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific topic within the course (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_assessments",
                        to="course.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MockInterview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("instructions", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(default=60, help_text="Duration in minutes"),
                ),
                ("total_marks", models.IntegerField(default=100)),
                ("passing_marks", models.IntegerField(default=60)),
                ("enable_proctoring", models.BooleanField(default=False)),
                (
                    "total_attempts",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of attempts made"
                    ),
                ),
                (
                    "question_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of question UUIDs from the Question model",
                    ),
                ),
                (
                    "publish_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("coding", "Coding"),
                            ("system_design", "System Design"),
                            ("aptitude", "Aptitude"),
                            ("behavioral", "Behavioral"),
                            ("domain_specific", "Domain Specific"),
                        ],
                        default="coding",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("scheduled_datetime", models.DateTimeField()),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Course this assessment belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_assessments",
                        to="course.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific topic within the course (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_assessments",
                        to="course.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_datetime"],
            },
        ),
        migrations.CreateModel(
            name="SkillTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("instructions", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(default=60, help_text="Duration in minutes"),
                ),
                ("total_marks", models.IntegerField(default=100)),
                ("passing_marks", models.IntegerField(default=60)),
                ("enable_proctoring", models.BooleanField(default=False)),
                (
                    "total_attempts",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of attempts made"
                    ),
                ),
                (
                    "question_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of question UUIDs from the Question model",
                    ),
                ),
                (
                    "publish_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Course this assessment belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_assessments",
                        to="course.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific topic within the course (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_assessments",
                        to="course.topic",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SkillTestSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("submitted", "Submitted"),
                            ("evaluated", "Evaluated"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("proctoring_events", models.JSONField(blank=True, default=list)),
                ("browser_info", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("marks", models.FloatField(blank=True, null=True)),
                (
                    "skill_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_test_submissions",
                        to="assessment.skilltest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "skill_test")},
            },
        ),
        migrations.CreateModel(
            name="MockInterviewSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("submitted", "Submitted"),
                            ("evaluated", "Evaluated"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("proctoring_events", models.JSONField(blank=True, default=list)),
                ("browser_info", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("marks", models.FloatField(blank=True, null=True)),
                (
                    "mock_interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_interview_submissions",
                        to="assessment.mockinterview",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "mock_interview")},
            },
        ),
        migrations.CreateModel(
            name="JobTestSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("submitted", "Submitted"),
                            ("evaluated", "Evaluated"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("proctoring_events", models.JSONField(blank=True, default=list)),
                ("browser_info", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("marks", models.FloatField(blank=True, null=True)),
                (
                    "job_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_test_submissions",
                        to="assessment.jobtest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "job_test")},
            },
        ),
        migrations.CreateModel(
            name="ContestSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("submitted", "Submitted"),
                            ("evaluated", "Evaluated"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("proctoring_events", models.JSONField(blank=True, default=list)),
                ("browser_info", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("marks", models.FloatField(blank=True, null=True)),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contest_submissions",
                        to="assessment.contest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "contest")},
            },
        ),
    ]
