# Generated by Django 4.2.7 on 2025-12-14 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0002_remove_question_mcq_correct_answer_index_and_more"),
        ("assessment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestsubmission",
            name="general_events",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="General submission events: session start/end, navigation, browser info, etc.",
            ),
        ),
        migrations.AddField(
            model_name="jobtestsubmission",
            name="general_events",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="General submission events: session start/end, navigation, browser info, etc.",
            ),
        ),
        migrations.AddField(
            model_name="mockinterviewsubmission",
            name="general_events",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="General submission events: session start/end, navigation, browser info, etc.",
            ),
        ),
        migrations.AddField(
            model_name="skilltestsubmission",
            name="general_events",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="General submission events: session start/end, navigation, browser info, etc.",
            ),
        ),
        migrations.AlterField(
            model_name="contestsubmission",
            name="proctoring_events",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Proctoring events: camera/mic status, face detection, violations, etc.",
            ),
        ),
        migrations.AlterField(
            model_name="jobtestsubmission",
            name="proctoring_events",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Proctoring events: camera/mic status, face detection, violations, etc.",
            ),
        ),
        migrations.AlterField(
            model_name="mockinterviewsubmission",
            name="proctoring_events",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Proctoring events: camera/mic status, face detection, violations, etc.",
            ),
        ),
        migrations.AlterField(
            model_name="skilltestsubmission",
            name="proctoring_events",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Proctoring events: camera/mic status, face detection, violations, etc.",
            ),
        ),
        migrations.CreateModel(
            name="SkillTestQuestionActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question_activities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Question-specific activities: [{'timestamp': '2024-12-14T10:00:00Z', 'activity_type': 'question_viewed', 'meta_data': {...}}]",
                    ),
                ),
                (
                    "navigation_activities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Navigation and focus activities: [{'timestamp': '2024-12-14T10:01:00Z', 'activity_type': 'tab_switched', 'meta_data': {...}}]",
                    ),
                ),
                (
                    "proctoring_activities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Proctoring events: [{'timestamp': '2024-12-14T10:02:00Z', 'activity_type': 'face_not_detected', 'meta_data': {...}}]",
                    ),
                ),
                (
                    "camera_snapshots",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Camera snapshot image paths with timestamps: [{'timestamp': '2024-12-14T10:00:00Z', 'image_path': '/media/snapshots/user123_q456_20241214100000.jpg', 'meta_data': {...}}]",
                    ),
                ),
                (
                    "alert_priority",
                    models.CharField(
                        choices=[
                            ("info", "Informational"),
                            ("low", "Low Priority"),
                            ("medium", "Medium Priority"),
                            ("high", "High Priority"),
                            ("critical", "Critical Priority"),
                        ],
                        default="info",
                        help_text="Priority level for alerts and violations",
                        max_length=10,
                    ),
                ),
                (
                    "answer_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Current answer content based on question type (MCQ selections, code, descriptive text)",
                    ),
                ),
                (
                    "answer_history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Answer change history: [{'timestamp': '2024-12-14T10:05:00Z', 'answer_data': {...}, 'is_auto_save': true}]",
                    ),
                ),
                (
                    "is_final_answer",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the current answer is final/submitted",
                    ),
                ),
                (
                    "answer_attempt_count",
                    models.IntegerField(
                        default=0, help_text="Number of times answer was modified"
                    ),
                ),
                ("marks_obtained", models.FloatField(blank=True, null=True)),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                ("auto_graded", models.BooleanField(default=False)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("grading_feedback", models.TextField(blank=True)),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="Browser session identifier",
                        max_length=100,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "total_question_time",
                    models.IntegerField(
                        default=0,
                        help_text="Total time spent on this question in seconds",
                    ),
                ),
                (
                    "violation_count",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of violations for this question",
                    ),
                ),
                (
                    "last_activity_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("has_violations", models.BooleanField(default=False)),
                ("violations_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_%(class)s_question_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_question_activities",
                        to="course.question",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_%(class)s_question_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skill_test_submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_test_question_activities",
                        to="assessment.skilltestsubmission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_question_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("skill_test_submission", "question")},
            },
        ),
        migrations.CreateModel(
            name="MockInterviewQuestionActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question_activities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Question-specific activities: [{'timestamp': '2024-12-14T10:00:00Z', 'activity_type': 'question_viewed', 'meta_data': {...}}]",
                    ),
                ),
                (
                    "navigation_activities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Navigation and focus activities: [{'timestamp': '2024-12-14T10:01:00Z', 'activity_type': 'tab_switched', 'meta_data': {...}}]",
                    ),
                ),
                (
                    "proctoring_activities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Proctoring events: [{'timestamp': '2024-12-14T10:02:00Z', 'activity_type': 'face_not_detected', 'meta_data': {...}}]",
                    ),
                ),
                (
                    "camera_snapshots",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Camera snapshot image paths with timestamps: [{'timestamp': '2024-12-14T10:00:00Z', 'image_path': '/media/snapshots/user123_q456_20241214100000.jpg', 'meta_data': {...}}]",
                    ),
                ),
                (
                    "alert_priority",
                    models.CharField(
                        choices=[
                            ("info", "Informational"),
                            ("low", "Low Priority"),
                            ("medium", "Medium Priority"),
                            ("high", "High Priority"),
                            ("critical", "Critical Priority"),
                        ],
                        default="info",
                        help_text="Priority level for alerts and violations",
                        max_length=10,
                    ),
                ),
                (
                    "answer_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Current answer content based on question type (MCQ selections, code, descriptive text)",
                    ),
                ),
                (
                    "answer_history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Answer change history: [{'timestamp': '2024-12-14T10:05:00Z', 'answer_data': {...}, 'is_auto_save': true}]",
                    ),
                ),
                (
                    "is_final_answer",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the current answer is final/submitted",
                    ),
                ),
                (
                    "answer_attempt_count",
                    models.IntegerField(
                        default=0, help_text="Number of times answer was modified"
                    ),
                ),
                ("marks_obtained", models.FloatField(blank=True, null=True)),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                ("auto_graded", models.BooleanField(default=False)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("grading_feedback", models.TextField(blank=True)),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="Browser session identifier",
                        max_length=100,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "total_question_time",
                    models.IntegerField(
                        default=0,
                        help_text="Total time spent on this question in seconds",
                    ),
                ),
                (
                    "violation_count",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of violations for this question",
                    ),
                ),
                (
                    "last_activity_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("has_violations", models.BooleanField(default=False)),
                ("violations_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_%(class)s_question_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mock_interview_submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_interview_question_activities",
                        to="assessment.mockinterviewsubmission",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_question_activities",
                        to="course.question",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_%(class)s_question_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_question_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("mock_interview_submission", "question")},
            },
        ),
        migrations.CreateModel(
            name="JobTestQuestionActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question_activities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Question-specific activities: [{'timestamp': '2024-12-14T10:00:00Z', 'activity_type': 'question_viewed', 'meta_data': {...}}]",
                    ),
                ),
                (
                    "navigation_activities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Navigation and focus activities: [{'timestamp': '2024-12-14T10:01:00Z', 'activity_type': 'tab_switched', 'meta_data': {...}}]",
                    ),
                ),
                (
                    "proctoring_activities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Proctoring events: [{'timestamp': '2024-12-14T10:02:00Z', 'activity_type': 'face_not_detected', 'meta_data': {...}}]",
                    ),
                ),
                (
                    "camera_snapshots",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Camera snapshot image paths with timestamps: [{'timestamp': '2024-12-14T10:00:00Z', 'image_path': '/media/snapshots/user123_q456_20241214100000.jpg', 'meta_data': {...}}]",
                    ),
                ),
                (
                    "alert_priority",
                    models.CharField(
                        choices=[
                            ("info", "Informational"),
                            ("low", "Low Priority"),
                            ("medium", "Medium Priority"),
                            ("high", "High Priority"),
                            ("critical", "Critical Priority"),
                        ],
                        default="info",
                        help_text="Priority level for alerts and violations",
                        max_length=10,
                    ),
                ),
                (
                    "answer_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Current answer content based on question type (MCQ selections, code, descriptive text)",
                    ),
                ),
                (
                    "answer_history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Answer change history: [{'timestamp': '2024-12-14T10:05:00Z', 'answer_data': {...}, 'is_auto_save': true}]",
                    ),
                ),
                (
                    "is_final_answer",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the current answer is final/submitted",
                    ),
                ),
                (
                    "answer_attempt_count",
                    models.IntegerField(
                        default=0, help_text="Number of times answer was modified"
                    ),
                ),
                ("marks_obtained", models.FloatField(blank=True, null=True)),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                ("auto_graded", models.BooleanField(default=False)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("grading_feedback", models.TextField(blank=True)),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="Browser session identifier",
                        max_length=100,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "total_question_time",
                    models.IntegerField(
                        default=0,
                        help_text="Total time spent on this question in seconds",
                    ),
                ),
                (
                    "violation_count",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of violations for this question",
                    ),
                ),
                (
                    "last_activity_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("has_violations", models.BooleanField(default=False)),
                ("violations_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_%(class)s_question_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_test_submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_test_question_activities",
                        to="assessment.jobtestsubmission",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_question_activities",
                        to="course.question",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_%(class)s_question_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_question_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("job_test_submission", "question")},
            },
        ),
        migrations.CreateModel(
            name="ContestQuestionActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question_activities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Question-specific activities: [{'timestamp': '2024-12-14T10:00:00Z', 'activity_type': 'question_viewed', 'meta_data': {...}}]",
                    ),
                ),
                (
                    "navigation_activities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Navigation and focus activities: [{'timestamp': '2024-12-14T10:01:00Z', 'activity_type': 'tab_switched', 'meta_data': {...}}]",
                    ),
                ),
                (
                    "proctoring_activities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Proctoring events: [{'timestamp': '2024-12-14T10:02:00Z', 'activity_type': 'face_not_detected', 'meta_data': {...}}]",
                    ),
                ),
                (
                    "camera_snapshots",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Camera snapshot image paths with timestamps: [{'timestamp': '2024-12-14T10:00:00Z', 'image_path': '/media/snapshots/user123_q456_20241214100000.jpg', 'meta_data': {...}}]",
                    ),
                ),
                (
                    "alert_priority",
                    models.CharField(
                        choices=[
                            ("info", "Informational"),
                            ("low", "Low Priority"),
                            ("medium", "Medium Priority"),
                            ("high", "High Priority"),
                            ("critical", "Critical Priority"),
                        ],
                        default="info",
                        help_text="Priority level for alerts and violations",
                        max_length=10,
                    ),
                ),
                (
                    "answer_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Current answer content based on question type (MCQ selections, code, descriptive text)",
                    ),
                ),
                (
                    "answer_history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Answer change history: [{'timestamp': '2024-12-14T10:05:00Z', 'answer_data': {...}, 'is_auto_save': true}]",
                    ),
                ),
                (
                    "is_final_answer",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the current answer is final/submitted",
                    ),
                ),
                (
                    "answer_attempt_count",
                    models.IntegerField(
                        default=0, help_text="Number of times answer was modified"
                    ),
                ),
                ("marks_obtained", models.FloatField(blank=True, null=True)),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                ("auto_graded", models.BooleanField(default=False)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("grading_feedback", models.TextField(blank=True)),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="Browser session identifier",
                        max_length=100,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "total_question_time",
                    models.IntegerField(
                        default=0,
                        help_text="Total time spent on this question in seconds",
                    ),
                ),
                (
                    "violation_count",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of violations for this question",
                    ),
                ),
                (
                    "last_activity_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("has_violations", models.BooleanField(default=False)),
                ("violations_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "contest_submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contest_question_activities",
                        to="assessment.contestsubmission",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_%(class)s_question_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_question_activities",
                        to="course.question",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_%(class)s_question_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_question_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("contest_submission", "question")},
            },
        ),
    ]
