# Generated by Django 4.2.7 on 2025-12-13 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_remove_question_mcq_correct_answer_index_and_more"),
        ("assessment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contest",
            name="course",
        ),
        migrations.RemoveField(
            model_name="contest",
            name="topic",
        ),
        migrations.RemoveField(
            model_name="jobtest",
            name="course",
        ),
        migrations.RemoveField(
            model_name="jobtest",
            name="topic",
        ),
        migrations.RemoveField(
            model_name="mockinterview",
            name="course",
        ),
        migrations.RemoveField(
            model_name="mockinterview",
            name="topic",
        ),
        migrations.AddField(
            model_name="contest",
            name="question_ids_random",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Random question configuration: {'mcq_single': 5, 'mcq_multiple': 3, 'coding': 2, 'descriptive': 1}",
            ),
        ),
        migrations.AddField(
            model_name="jobtest",
            name="question_ids_random",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Random question configuration: {'mcq_single': 5, 'mcq_multiple': 3, 'coding': 2, 'descriptive': 1}",
            ),
        ),
        migrations.AddField(
            model_name="mockinterview",
            name="question_ids_random",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Random question configuration: {'mcq_single': 5, 'mcq_multiple': 3, 'coding': 2, 'descriptive': 1}",
            ),
        ),
        migrations.AddField(
            model_name="skilltest",
            name="question_ids_random",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Random question configuration: {'mcq_single': 5, 'mcq_multiple': 3, 'coding': 2, 'descriptive': 1}",
            ),
        ),
        migrations.AlterField(
            model_name="skilltest",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Course this skill test belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skill_test_assessments",
                to="course.course",
            ),
        ),
        migrations.AlterField(
            model_name="skilltest",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific topic within the course (optional)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skill_test_assessments",
                to="course.topic",
            ),
        ),
    ]
