# Generated by Django 4.2.7 on 2025-12-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0002_contestsubmission_general_events_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestquestionactivity",
            name="plagiarism_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Plagiarism check results: {'is_plagiarized': true, 'similarity_score': 0.95, 'matched_with': 'submission_id'}",
            ),
        ),
        migrations.AddField(
            model_name="jobtestquestionactivity",
            name="plagiarism_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Plagiarism check results: {'is_plagiarized': true, 'similarity_score': 0.95, 'matched_with': 'submission_id'}",
            ),
        ),
        migrations.AddField(
            model_name="mockinterviewquestionactivity",
            name="plagiarism_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Plagiarism check results: {'is_plagiarized': true, 'similarity_score': 0.95, 'matched_with': 'submission_id'}",
            ),
        ),
        migrations.AddField(
            model_name="skilltestquestionactivity",
            name="plagiarism_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Plagiarism check results: {'is_plagiarized': true, 'similarity_score': 0.95, 'matched_with': 'submission_id'}",
            ),
        ),
    ]
