# Generated by Django 4.2.7 on 2025-12-20 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_contestquestionactivity_plagiarism_data_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skilltestsubmission',
            unique_together=set(),
        ),
    ]
