# Generated by Django 4.2.7 on 2025-12-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0004_alter_skilltestsubmission_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="max_attempts",
            field=models.PositiveIntegerField(
                default=3, help_text="Maximum number of attempts allowed per user"
            ),
        ),
        migrations.AddField(
            model_name="jobtest",
            name="max_attempts",
            field=models.PositiveIntegerField(
                default=3, help_text="Maximum number of attempts allowed per user"
            ),
        ),
        migrations.AddField(
            model_name="mockinterview",
            name="max_attempts",
            field=models.PositiveIntegerField(
                default=3, help_text="Maximum number of attempts allowed per user"
            ),
        ),
        migrations.AddField(
            model_name="skilltest",
            name="max_attempts",
            field=models.PositiveIntegerField(
                default=3, help_text="Maximum number of attempts allowed per user"
            ),
        ),
    ]
