# Generated by Django 4.2.7 on 2025-12-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0005_contest_max_attempts_jobtest_max_attempts_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mockinterview",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="mockinterview",
            name="difficulty",
        ),
        migrations.RemoveField(
            model_name="mockinterview",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="mockinterview",
            name="enable_proctoring",
        ),
        migrations.RemoveField(
            model_name="mockinterview",
            name="max_attempts",
        ),
        migrations.RemoveField(
            model_name="mockinterview",
            name="passing_marks",
        ),
        migrations.RemoveField(
            model_name="mockinterview",
            name="scheduled_datetime",
        ),
        migrations.RemoveField(
            model_name="mockinterview",
            name="status",
        ),
        migrations.RemoveField(
            model_name="mockinterview",
            name="total_attempts",
        ),
        migrations.RemoveField(
            model_name="mockinterview",
            name="total_marks",
        ),
        migrations.RemoveField(
            model_name="mockinterview",
            name="type",
        ),
        migrations.AddField(
            model_name="mockinterview",
            name="ai_coding_question_count",
            field=models.IntegerField(
                default=1, help_text="Number of coding questions AI should ask"
            ),
        ),
        migrations.AddField(
            model_name="mockinterview",
            name="ai_generation_mode",
            field=models.CharField(
                choices=[
                    ("full_ai", "Full AI Generated"),
                    ("mixed", "Mixed (AI + Predefined)"),
                    ("predefined", "Predefined Questions Only"),
                ],
                default="full_ai",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mockinterview",
            name="ai_verbal_question_count",
            field=models.IntegerField(
                default=5, help_text="Number of verbal questions AI should ask"
            ),
        ),
        migrations.AddField(
            model_name="mockinterview",
            name="audio_settings",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional audio settings"
            ),
        ),
        migrations.AddField(
            model_name="mockinterview",
            name="max_duration",
            field=models.IntegerField(
                default=30, help_text="Maximum duration in minutes"
            ),
        ),
        migrations.AddField(
            model_name="mockinterview",
            name="optional_skills",
            field=models.JSONField(
                blank=True, default=list, help_text="List of optional skills"
            ),
        ),
        migrations.AddField(
            model_name="mockinterview",
            name="required_skills",
            field=models.JSONField(
                blank=True, default=list, help_text="List of required skills"
            ),
        ),
        migrations.AddField(
            model_name="mockinterview",
            name="voice_speed",
            field=models.FloatField(
                default=1.0, help_text="Voice playback speed (0.5 to 2.0)"
            ),
        ),
        migrations.AddField(
            model_name="mockinterview",
            name="voice_type",
            field=models.CharField(
                choices=[("junnu", "Junnu (Male IN)"), ("munnu", "Munnu (Female US)")],
                default="junnu",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mockinterview",
            name="questions_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Questions configuration by category: {'mcq_single': ['uuid1'], ...}",
            ),
        ),
        migrations.AlterField(
            model_name="mockinterview",
            name="questions_random_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Random question configuration: {'mcq_single': 5, ...}",
            ),
        ),
    ]
