# Generated by Django 4.2.7 on 2025-12-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0006_alter_mockinterview_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mockinterviewsubmission",
            name="experience_level",
            field=models.CharField(
                choices=[
                    ("intern", "Intern"),
                    ("beginner", "Beginner (0-1 years)"),
                    ("1_3_years", "Intermediate (1-3 years)"),
                    ("3_plus_years", "Experienced (3+ years)"),
                ],
                default="beginner",
                help_text="Candidate's self-declared experience level for this interview",
                max_length=20,
            ),
        ),
    ]
