# Generated by Django 4.2.7 on 2025-12-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0007_mockinterviewsubmission_experience_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="mockinterviewsubmission",
            name="selected_duration",
            field=models.IntegerField(
                default=0, help_text="Duration selected by the user in minutes"
            ),
        ),
    ]
