# Generated by Django 4.2.7 on 2025-12-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0008_mockinterviewsubmission_selected_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="mockinterview",
            name="interviewer_name",
            field=models.CharField(
                default="Junnu", help_text="Name of the AI interviewer", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="mockinterview",
            name="interviewer_voice_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Specific voice ID for TTS",
                max_length=255,
            ),
        ),
    ]
