# Generated by Django 4.2.7 on 2025-12-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0009_mockinterview_interviewer_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mockinterview",
            name="ai_percentage",
            field=models.IntegerField(
                default=100, help_text="Percentage of AI generated questions (0-100)"
            ),
        ),
    ]
