# Generated by Django 4.2.7 on 2025-12-27 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ai_assistant", "0002_create_default_agents"),
        ("assessment", "0010_mockinterview_ai_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="mockinterviewsubmission",
            name="chat_session",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mock_interview_submission",
                to="ai_assistant.chatsession",
            ),
        ),
        migrations.AddField(
            model_name="mockinterviewsubmission",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
    ]
