# Generated by Django 4.2.7 on 2025-12-28 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0004_alter_course_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assessment", "0011_mockinterviewsubmission_chat_session_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearnOrPracticeSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("submitted", "Submitted"),
                            ("evaluated", "Evaluated"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                (
                    "submission_type",
                    models.CharField(
                        choices=[("learn", "Learn"), ("practice", "Practice")],
                        default="practice",
                        help_text="Type of submission - learn or practice",
                        max_length=20,
                    ),
                ),
                (
                    "answer_latest",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Latest answer content including code, language, and test cases",
                    ),
                ),
                (
                    "answer_history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Complete submission history: [{'timestamp': '2024-12-14T10:05:00Z', 'answer_data': {...}, 'is_auto_save': false, 'execution_results': {...}}]",
                    ),
                ),
                (
                    "answer_attempt_count",
                    models.IntegerField(
                        default=0, help_text="Number of times answer was modified"
                    ),
                ),
                (
                    "execution_output",
                    models.TextField(blank=True, help_text="Code execution output"),
                ),
                (
                    "plagiarism_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Plagiarism check results: {'is_plagiarized': true, 'similarity_score': 0.95, 'matched_with': 'submission_id'}",
                    ),
                ),
                (
                    "evaluation_results",
                    models.JSONField(
                        blank=True, default=dict, help_text="Detailed test case results"
                    ),
                ),
                ("marks_obtained", models.FloatField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Course this submission belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learn_or_practice_submissions",
                        to="course.course",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="The coding question being solved",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learn_or_practice_submissions",
                        to="course.question",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Topic this submission belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learn_or_practice_submissions",
                        to="course.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learn_or_practice_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "question", "submission_type")},
            },
        ),
    ]
