# Generated by Django 4.2.7 on 2025-12-28 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0012_learnorpracticesubmission"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LearnOrPracticeSubmission",
        ),
    ]
