# Generated by Django 4.2.7 on 2025-12-28 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0004_alter_course_category"),
        ("assessment", "0012_codepracticequestionsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="codepracticequestionsubmission",
            name="answer_latest",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Latest answer content including code, language, and test cases",
            ),
        ),
        migrations.AlterField(
            model_name="codepracticequestionsubmission",
            name="answer_history",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Complete submission history: [{'timestamp': '2024-12-14T10:05:00Z', 'answer_data': {...}, 'is_auto_save': false, 'execution_results': {...}}]",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="codepracticequestionsubmission",
            unique_together={("user", "question")},
        ),
        migrations.RemoveField(
            model_name="codepracticequestionsubmission",
            name="answer_data",
        ),
        migrations.RemoveField(
            model_name="codepracticequestionsubmission",
            name="programming_language",
        ),
    ]
