# Generated by Django 5.2.7 on 2026-01-06 15:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0013_remove_learnorpracticesubmission'),
        ('course', '0006_studentcodepractice_ai_help_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('duration', models.IntegerField(default=60, help_text='Duration in minutes')),
                ('total_marks', models.IntegerField(default=100)),
                ('passing_marks', models.IntegerField(default=60)),
                ('enable_proctoring', models.BooleanField(default=False)),
                ('total_attempts', models.PositiveIntegerField(default=0, help_text='Total number of attempts made')),
                ('max_attempts', models.PositiveIntegerField(default=3, help_text='Maximum number of attempts allowed per user')),
                ('questions_config', models.JSONField(blank=True, default=dict, help_text="Questions configuration by category: {'mcq_single': ['uuid1', 'uuid2'], 'mcq_multiple': ['uuid3'], 'coding': ['uuid4'], 'descriptive': ['uuid5']}")),
                ('questions_random_config', models.JSONField(blank=True, default=dict, help_text="Random question configuration: {'mcq_single': 5, 'mcq_multiple': 3, 'coding': 2, 'descriptive': 1}")),
                ('publish_status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('certificate_template', models.CharField(blank=True, help_text='Path to certificate template image/pdf', max_length=255)),
                ('course', models.OneToOneField(help_text='Course this certification exam belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='certification_exam', to='course.course')),
                ('created_by', models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificationSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('submitted', 'Submitted'), ('evaluated', 'Evaluated'), ('cancelled', 'Cancelled')], default='started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('general_events', models.JSONField(blank=True, default=list, help_text='General submission events: session start/end, navigation, browser info, etc.')),
                ('proctoring_events', models.JSONField(blank=True, default=list, help_text='Proctoring events: camera/mic status, face detection, violations, etc.')),
                ('browser_info', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('marks', models.FloatField(blank=True, null=True)),
                ('certification_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_submissions', to='assessment.certificationexam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('certificate_url', models.URLField(blank=True, help_text='URL to downloaded certificate')),
                ('certificate_id', models.CharField(help_text='Unique certificate identifier', max_length=50, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('certification_exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='assessment.certificationexam')),
                ('submission', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate', to='assessment.certificationsubmission')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificationQuestionActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_activities', models.JSONField(blank=True, default=list, help_text="Question-specific activities: [{'timestamp': '2024-12-14T10:00:00Z', 'activity_type': 'question_viewed', 'meta_data': {...}}]")),
                ('navigation_activities', models.JSONField(blank=True, default=list, help_text="Navigation and focus activities: [{'timestamp': '2024-12-14T10:01:00Z', 'activity_type': 'tab_switched', 'meta_data': {...}}]")),
                ('proctoring_activities', models.JSONField(blank=True, default=list, help_text="Proctoring events: [{'timestamp': '2024-12-14T10:02:00Z', 'activity_type': 'face_not_detected', 'meta_data': {...}}]")),
                ('camera_snapshots', models.JSONField(blank=True, default=list, help_text="Camera snapshot image paths with timestamps: [{'timestamp': '2024-12-14T10:00:00Z', 'image_path': '/media/snapshots/user123_q456_20241214100000.jpg', 'meta_data': {...}}]")),
                ('alert_priority', models.CharField(choices=[('info', 'Informational'), ('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('critical', 'Critical Priority')], default='info', help_text='Priority level for alerts and violations', max_length=10)),
                ('answer_data', models.JSONField(blank=True, default=dict, help_text='Current answer content based on question type (MCQ selections, code, descriptive text)')),
                ('answer_history', models.JSONField(blank=True, default=list, help_text="Answer change history: [{'timestamp': '2024-12-14T10:05:00Z', 'answer_data': {...}, 'is_auto_save': true}]")),
                ('is_final_answer', models.BooleanField(default=False, help_text='Whether the current answer is final/submitted')),
                ('answer_attempt_count', models.IntegerField(default=0, help_text='Number of times answer was modified')),
                ('plagiarism_data', models.JSONField(blank=True, default=dict, help_text="Plagiarism check results: {'is_plagiarized': true, 'similarity_score': 0.95, 'matched_with': 'submission_id'}")),
                ('marks_obtained', models.FloatField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('auto_graded', models.BooleanField(default=False)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('grading_feedback', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, help_text='Browser session identifier', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('total_question_time', models.IntegerField(default=0, help_text='Total time spent on this question in seconds')),
                ('violation_count', models.IntegerField(default=0, help_text='Total number of violations for this question')),
                ('last_activity_timestamp', models.DateTimeField(blank=True, null=True)),
                ('has_violations', models.BooleanField(default=False)),
                ('violations_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_%(class)s_question_activities', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_question_activities', to='course.question')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_%(class)s_question_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_question_activities', to=settings.AUTH_USER_MODEL)),
                ('certification_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_question_activities', to='assessment.certificationsubmission')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('certification_submission', 'question')},
            },
        ),
    ]
