# Generated by Django 4.2.7 on 2025-12-31 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0013_remove_learnorpracticesubmission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contestquestionactivity",
            name="is_final_answer",
        ),
        migrations.RemoveField(
            model_name="contestquestionactivity",
            name="plagiarism_data",
        ),
        migrations.RemoveField(
            model_name="jobtestquestionactivity",
            name="is_final_answer",
        ),
        migrations.RemoveField(
            model_name="jobtestquestionactivity",
            name="plagiarism_data",
        ),
        migrations.RemoveField(
            model_name="mockinterviewquestionactivity",
            name="is_final_answer",
        ),
        migrations.RemoveField(
            model_name="mockinterviewquestionactivity",
            name="plagiarism_data",
        ),
        migrations.RemoveField(
            model_name="skilltestquestionactivity",
            name="is_final_answer",
        ),
        migrations.RemoveField(
            model_name="skilltestquestionactivity",
            name="plagiarism_data",
        ),
    ]
