# Generated by Django 4.2.7 on 2026-01-07 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0006_studentcodepractice_ai_help_count"),
        ("assessment", "0014_certificationexam_certificationsubmission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificationexam",
            name="end_datetime",
            field=models.DateTimeField(
                blank=True, help_text="When the exam expires", null=True
            ),
        ),
        migrations.AddField(
            model_name="certificationexam",
            name="start_datetime",
            field=models.DateTimeField(
                blank=True, help_text="When the exam becomes available", null=True
            ),
        ),
        migrations.AlterField(
            model_name="certificationexam",
            name="course",
            field=models.ForeignKey(
                help_text="Course this certification exam belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certification_exams",
                to="course.course",
            ),
        ),
    ]
