# Generated by Django 4.2.7 on 2025-12-31 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("code_editor", "0001_initial"),
        ("assessment", "0014_remove_contestquestionactivity_is_final_answer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestquestionactivity",
            name="code_submission",
            field=models.ForeignKey(
                blank=True,
                help_text="Code submission for coding questions only",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_question_activities",
                to="code_editor.codesubmission",
            ),
        ),
        migrations.AddField(
            model_name="contestquestionactivity",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("mcq_single", "MCQ - Single Answer"),
                    ("mcq_multiple", "MCQ - Multiple Answers"),
                    ("coding", "Coding Problem"),
                    ("descriptive", "Descriptive Question"),
                ],
                default="mcq_single",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobtestquestionactivity",
            name="code_submission",
            field=models.ForeignKey(
                blank=True,
                help_text="Code submission for coding questions only",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_question_activities",
                to="code_editor.codesubmission",
            ),
        ),
        migrations.AddField(
            model_name="jobtestquestionactivity",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("mcq_single", "MCQ - Single Answer"),
                    ("mcq_multiple", "MCQ - Multiple Answers"),
                    ("coding", "Coding Problem"),
                    ("descriptive", "Descriptive Question"),
                ],
                default="mcq_single",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mockinterviewquestionactivity",
            name="code_submission",
            field=models.ForeignKey(
                blank=True,
                help_text="Code submission for coding questions only",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_question_activities",
                to="code_editor.codesubmission",
            ),
        ),
        migrations.AddField(
            model_name="mockinterviewquestionactivity",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("mcq_single", "MCQ - Single Answer"),
                    ("mcq_multiple", "MCQ - Multiple Answers"),
                    ("coding", "Coding Problem"),
                    ("descriptive", "Descriptive Question"),
                ],
                default="mcq_single",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="skilltestquestionactivity",
            name="code_submission",
            field=models.ForeignKey(
                blank=True,
                help_text="Code submission for coding questions only",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_question_activities",
                to="code_editor.codesubmission",
            ),
        ),
        migrations.AddField(
            model_name="skilltestquestionactivity",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("mcq_single", "MCQ - Single Answer"),
                    ("mcq_multiple", "MCQ - Multiple Answers"),
                    ("coding", "Coding Problem"),
                    ("descriptive", "Descriptive Question"),
                ],
                default="mcq_single",
                max_length=20,
            ),
        ),
    ]
