# Generated by Django 4.2.7 on 2025-12-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="mcq_correct_answer_index",
        ),
        migrations.AlterField(
            model_name="question",
            name="mcq_options",
            field=models.JSONField(
                blank=True,
                help_text="Options for MCQ questions with answer info. Format: [{'text': 'Option 1', 'is_correct': True}, {'text': 'Option 2', 'is_correct': False}]",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("mcq_single", "MCQ - Single Answer"),
                    ("mcq_multiple", "MCQ - Multiple Answers"),
                    ("coding", "Coding Problem"),
                    ("descriptive", "Descriptive Question"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subtopic",
            unique_together={("topic", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="topic",
            unique_together={("course", "name")},
        ),
    ]
