# Generated by Django 4.2.7 on 2025-11-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["category", "-created_at"]},
        ),
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.CharField(
                choices=[
                    ("fundamentals", "Fundamentals"),
                    ("programming_languages", "Programming Languages"),
                    ("databases", "Databases"),
                    ("ai_tools", "AI Tools"),
                ],
                default="fundamentals",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
