# Generated by Django 4.2.7 on 2025-12-14 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0002_remove_question_mcq_correct_answer_index_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCourseProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_videos_watched",
                    models.BooleanField(
                        default=False,
                        help_text="Whether all videos in this subtopic have been watched",
                    ),
                ),
                (
                    "quiz_answers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Quiz answers: {'question_id': {'user_answer': ['A', 'B'], 'correct_answer': ['A', 'C'], 'is_correct': false, 'timestamp': '2024-12-14T10:00:00Z'}}",
                    ),
                ),
                (
                    "quiz_score",
                    models.FloatField(
                        default=0.0, help_text="Quiz score as percentage (0-100)"
                    ),
                ),
                ("is_quiz_completed", models.BooleanField(default=False)),
                (
                    "coding_answers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Coding answers: {'question_id': {'user_code': 'def solution()...', 'language': 'python', 'test_results': {...}, 'is_correct': true, 'timestamp': '2024-12-14T10:00:00Z'}}",
                    ),
                ),
                (
                    "coding_score",
                    models.FloatField(
                        default=0.0, help_text="Coding score as percentage (0-100)"
                    ),
                ),
                ("is_coding_completed", models.BooleanField(default=False)),
                (
                    "progress_percent",
                    models.FloatField(
                        default=0.0,
                        help_text="Overall progress percentage considering videos + quiz + coding (0-100)",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this subtopic is fully completed",
                    ),
                ),
                (
                    "is_current_subtopic",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the current subtopic the user is working on",
                    ),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(
                        auto_now=True, help_text="Last time user accessed this subtopic"
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="course.course",
                    ),
                ),
                (
                    "subtopic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="course.subtopic",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="course.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("user", "subtopic")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="learnprogress",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="learnprogress",
            name="subtopic",
        ),
        migrations.RemoveField(
            model_name="learnprogress",
            name="user",
        ),
        migrations.DeleteModel(
            name="CourseContinue",
        ),
        migrations.DeleteModel(
            name="LearnProgress",
        ),
    ]
