# Generated by Django 4.2.7 on 2025-12-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0003_usercourseprogress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.CharField(
                choices=[
                    ("fundamentals", "Fundamentals"),
                    ("programming_languages", "Programming Languages"),
                    ("databases", "Databases"),
                    ("ai_tools", "AI Tools"),
                    ("web_development", "Web Development"),
                ],
                max_length=50,
            ),
        ),
    ]
