# Generated by Django 4.2.7 on 2025-11-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0003_video_quiz_note_codingproblem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="correct_answer",
        ),
        migrations.AddField(
            model_name="quiz",
            name="correct_answer_index",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
