# Generated by Django 4.2.7 on 2025-11-08 18:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0004_remove_quiz_correct_answer_quiz_correct_answer_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subtopic",
            name="video_url",
        ),
    ]
