# Generated by Django 4.2.7 on 2025-12-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_studentcodepractice'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcodepractice',
            name='ai_help_count',
            field=models.IntegerField(default=0, help_text='Number of times AI help was used'),
        ),
    ]
