# Generated by Django 4.2.7 on 2025-11-13 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0005_remove_subtopic_video_url"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subtopic",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="topic",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="course",
            name="assigned_admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
