# Generated by Django 4.2.7 on 2025-11-16 11:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_update_coding_problem_test_cases"),
        ("course", "0006_alter_subtopic_unique_together_and_more"),
    ]

    operations = []
