<<<<<<< HEAD
# Generated by Django 4.2.7 on 2025-11-18 10:22
=======
# Generated by Django 4.2.7 on 2025-11-19 06:34
>>>>>>> 7d78b66 (feat(jobs): add jobs in Frontend)

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial_squashed_0007_merge_20251116_1145"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.CharField(
                choices=[
                    ("fundamentals", "Fundamentals"),
                    ("programming_languages", "Programming Languages"),
                    ("databases", "Databases"),
                    ("ai_tools", "AI Tools"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="correct_answer_index",
            field=models.PositiveIntegerField(),
        ),
    ]
