# Generated by Django 4.2.7 on 2025-11-18 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial_squashed_0007_merge_20251116_1145"),
    ]

    operations = [
        migrations.AddField(
            model_name="codingproblem",
            name="category",
            field=models.CharField(
                choices=[
                    ("learn_certify", "Learn & Certify"),
                    ("practice", "Practice Questions"),
                    ("skill_test", "Skill Test"),
                ],
                default="learn_certify",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="codingproblem",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coding_problems_topic",
                to="course.topic",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="category",
            field=models.CharField(
                choices=[
                    ("learn_certify", "Learn & Certify"),
                    ("practice", "Practice Questions"),
                    ("skill_test", "Skill Test"),
                ],
                default="learn_certify",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quiz",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes_topic",
                to="course.topic",
            ),
        ),
        migrations.AlterField(
            model_name="codingproblem",
            name="sub_topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coding_problems",
                to="course.subtopic",
            ),
        ),
        migrations.AlterField(
            model_name="codingproblem",
            name="test_cases_advanced",
            field=models.JSONField(default=list, help_text="Advanced test cases"),
        ),
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.CharField(
                choices=[
                    ("fundamentals", "Fundamentals"),
                    ("programming_languages", "Programming Languages"),
                    ("databases", "Databases"),
                    ("ai_tools", "AI Tools"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="correct_answer_index",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="sub_topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="course.subtopic",
            ),
        ),
    ]
