# Generated by Django 4.2.7 on 2025-11-21 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0008_alter_course_category_and_more"),
        ("course", "0008_codingproblem_category_codingproblem_topic_and_more"),
    ]

    operations = []
