# Generated by Django 4.2.7 on 2025-11-30 17:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0011_add_question_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="codingproblem",
            name="sub_topic",
        ),
        migrations.RemoveField(
            model_name="codingproblem",
            name="topic",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="sub_topic",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="topic",
        ),
        migrations.RenameIndex(
            model_name="question",
            new_name="course_ques_type_15a593_idx",
            old_name="course_ques_type_b8c8a5_idx",
        ),
        migrations.RenameIndex(
            model_name="question",
            new_name="course_ques_difficu_960ef6_idx",
            old_name="course_ques_difficu_8f4b2a_idx",
        ),
        migrations.RenameIndex(
            model_name="question",
            new_name="course_ques_course__d54723_idx",
            old_name="course_ques_course__c8e8f1_idx",
        ),
        migrations.DeleteModel(
            name="CodingProblem",
        ),
        migrations.DeleteModel(
            name="Quiz",
        ),
    ]
