# Generated by Django 4.2.7 on 2025-12-03 17:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0012_remove_codingproblem_sub_topic_and_more"),
    ]

    operations = []
