# Generated by Django 4.2.7 on 2025-12-03 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0013_merge_20251203_1718"),
        ("course", "0013_update_question_categories_help_text"),
    ]

    operations = []
