# Generated by Django 4.2.7 on 2025-12-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0014_merge_20251203_1751"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="categories",
            field=models.JSONField(
                default=list,
                help_text="List of categories this question belongs to (learn, skill_test, contest)",
            ),
        ),
    ]
