# Generated by Django 4.2.7 on 2025-11-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial_with_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("admin_content", "Content Administrator"),
                    ("admin", "Administrator"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
