# Generated by Django 4.2.7 on 2025-11-15 15:48

from django.db import migrations, models


def update_roles(apps, schema_editor):
    """Update existing admin_content roles to instructor"""
    User = apps.get_model('authentication', 'User')
    User.objects.filter(role='admin_content').update(role='instructor')


def reverse_update_roles(apps, schema_editor):
    """Reverse the role update"""
    User = apps.get_model('authentication', 'User')
    User.objects.filter(role='instructor').update(role='admin_content')


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_profile_gender"),
    ]

    operations = [
        # First update the data
        migrations.RunPython(update_roles, reverse_update_roles),
        
        # Then update the field choices
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('student', 'Student'),
                    ('instructor', 'Instructor'),
                    ('recruiter', 'Recruiter'),
                    ('admin', 'Administrator'),
                ],
                default='student',
                max_length=20
            ),
        ),
    ]
