# Generated by Django 4.2.7 on 2025-11-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_rename_bio_profile_about_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="level",
            field=models.CharField(
                choices=[
                    ("Beginner", "Beginner"),
                    ("Intermediate", "Intermediate"),
                    ("Advanced", "Advanced"),
                ],
                max_length=100,
            ),
        ),
    ]
