# Generated by Django 4.2.7 on 2025-12-31 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("course", "0005_studentcodepractice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeSubmission",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.TextField()),
                ("language", models.CharField(max_length=50)),
                ("total_test_cases", models.IntegerField(default=0)),
                ("passed_test_cases", models.IntegerField(default=0)),
                ("execution_time_ms", models.FloatField(default=0)),
                ("peak_memory_kb", models.FloatField(default=0)),
                ("score_percent", models.FloatField(default=0)),
                ("marks", models.FloatField(default=0)),
                ("plagiarism_flagged", models.BooleanField(default=False)),
                ("max_similarity", models.FloatField(default=0)),
                ("test_results_basic", models.JSONField(blank=True, default=list)),
                ("test_results_advanced", models.JSONField(blank=True, default=list)),
                ("test_results_custom", models.JSONField(blank=True, default=list)),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_submissions",
                        to="course.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
