# Generated by Django 4.2.7 on 2025-12-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("domain", models.CharField(blank=True, max_length=255, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("size", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("work_type", models.CharField(max_length=50)),
                ("job_type", models.CharField(max_length=50)),
                ("experience_level", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("skills", models.JSONField(blank=True, default=list)),
                ("responsibilities", models.JSONField(blank=True, default=list)),
                ("required_skills", models.JSONField(blank=True, default=list)),
                ("preferred_skills", models.JSONField(blank=True, default=list)),
                ("benefits", models.JSONField(blank=True, default=list)),
                ("company_info", models.JSONField(blank=True, default=dict)),
                (
                    "company_size",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("logo", models.URLField(blank=True, null=True)),
                ("salary", models.CharField(max_length=255)),
                ("posted_date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
