# Generated by Django 4.2.7 on 2025-11-16 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Remote", "Remote"),
                            ("Hybrid", "Hybrid"),
                            ("Onsite", "Onsite"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("Fresher", "Fresher"),
                            ("0-2 yrs", "0-2 yrs"),
                            ("2-5 yrs", "2-5 yrs"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("Full-time", "Full-time"),
                            ("Internship", "Internship"),
                            ("Contract", "Contract"),
                        ],
                        max_length=50,
                    ),
                ),
                ("skills", models.JSONField(blank=True, default=list)),
                ("company_size", models.CharField(blank=True, max_length=50)),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("posted_date", models.DateTimeField(auto_now_add=True)),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
