# Generated by Django 4.2.7 on 2025-12-29 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_remove_certification_profile_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_ctc",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "expected_ctc",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("total_experience_years", models.PositiveIntegerField(default=0)),
                ("total_experience_months", models.PositiveIntegerField(default=0)),
                (
                    "notice_period",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("15_days", "15 Days"),
                            ("30_days", "30 Days"),
                            ("60_days", "60 Days"),
                            ("90_days", "90 Days"),
                        ],
                        default="30_days",
                        max_length=20,
                    ),
                ),
                ("available_from", models.DateField(blank=True, null=True)),
                (
                    "preferred_employment_types",
                    models.JSONField(blank=True, default=list),
                ),
                ("preferred_locations", models.JSONField(blank=True, default=list)),
                ("open_to_remote", models.BooleanField(default=False)),
                (
                    "highest_education",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high_school", "High School"),
                            ("diploma", "Diploma"),
                            ("bachelor", "Bachelor's Degree"),
                            ("master", "Master's Degree"),
                            ("phd", "PhD"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("domain", models.CharField(blank=True, max_length=100, null=True)),
                ("preferred_company_types", models.JSONField(blank=True, default=list)),
                ("is_actively_looking", models.BooleanField(default=True)),
                ("last_active", models.DateTimeField(auto_now=True)),
                ("resume_file", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_profile",
                        to="authentication.profile",
                    ),
                ),
            ],
            options={
                "db_table": "job_profile",
            },
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("paused", "Paused"),
                    ("closed", "Closed"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SocialLinks",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("github", models.URLField(blank=True, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("portfolio", models.URLField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="authentication.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Beginner", "Beginner"),
                            ("Intermediate", "Intermediate"),
                            ("Advanced", "Advanced"),
                        ],
                        max_length=100,
                    ),
                ),
                ("percentage", models.IntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="authentication.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("role", models.CharField(max_length=255)),
                ("tech_stack", models.JSONField(default=list)),
                ("github_link", models.URLField(blank=True, null=True)),
                ("live_link", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="authentication.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("duration", models.CharField(max_length=100)),
                ("description_list", models.JSONField(default=list)),
                ("technologies", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="authentication.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("institution", models.CharField(max_length=255)),
                ("degree", models.CharField(max_length=255)),
                ("field", models.CharField(max_length=255)),
                ("duration", models.CharField(max_length=100)),
                ("cgpa", models.CharField(blank=True, max_length=10, null=True)),
                ("start_year", models.IntegerField(blank=True, null=True)),
                ("end_year", models.IntegerField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="authentication.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("issuer", models.CharField(max_length=255)),
                ("completion_date", models.CharField(max_length=100)),
                ("certificate_file", models.URLField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="authentication.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CandidateSearchLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("search_filters", models.JSONField(default=dict)),
                ("results_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_search_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "candidate_search_log",
            },
        ),
        migrations.CreateModel(
            name="JobSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("skill_name", models.CharField(max_length=100)),
                (
                    "proficiency",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        max_length=20,
                    ),
                ),
                ("years_of_experience", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_skills",
                        to="job.jobprofile",
                    ),
                ),
            ],
            options={
                "db_table": "candidate_job_skill",
                "unique_together": {("job_profile", "skill_name")},
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_bookmarked", models.BooleanField(default=False)),
                ("is_applied", models.BooleanField(default=False)),
                ("cover_letter", models.TextField(blank=True, null=True)),
                (
                    "resume_file",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                ("portfolio_url", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("screening_test_completed", "Screening Test Completed"),
                            ("under_review", "Under Review"),
                            ("shortlisted", "Shortlisted"),
                            ("interview_scheduled", "Interview Scheduled"),
                            ("interviewed", "Interviewed"),
                            ("selected", "Selected"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        max_length=31,
                        null=True,
                    ),
                ),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("screening_responses", models.JSONField(blank=True, default=dict)),
                ("recruiter_notes", models.TextField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, null=True)),
                ("interview_scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("interview_feedback", models.TextField(blank=True, null=True)),
                (
                    "expected_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "expected_currency",
                    models.CharField(
                        choices=[
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("available_from", models.DateField(blank=True, null=True)),
                (
                    "notice_period_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="job.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_at"],
                "unique_together": {("job", "applicant")},
            },
        ),
    ]
