# Generated by Django 4.2.7 on 2025-11-19 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="company_size",
        ),
        migrations.RemoveField(
            model_name="job",
            name="posted_by",
        ),
        migrations.RemoveField(
            model_name="job",
            name="salary_max",
        ),
        migrations.RemoveField(
            model_name="job",
            name="salary_min",
        ),
        migrations.AddField(
            model_name="job",
            name="benefits",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="job",
            name="company_info",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="job",
            name="preferred_skills",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="job",
            name="required_skills",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="job",
            name="responsibilities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_range",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="work_type",
            field=models.CharField(
                choices=[
                    ("Remote", "Remote"),
                    ("Hybrid", "Hybrid"),
                    ("Onsite", "Onsite"),
                ],
                default=django.utils.timezone.now,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="experience_level",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="job",
            name="posted_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="skills",
            field=models.JSONField(default=list),
        ),
    ]
