# Generated by Django 4.2.7 on 2025-12-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0002_jobapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="is_applied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="is_bookmarked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="applied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("screening_test_completed", "Screening Test Completed"),
                    ("under_review", "Under Review"),
                    ("shortlisted", "Shortlisted"),
                    ("interview_scheduled", "Interview Scheduled"),
                    ("interviewed", "Interviewed"),
                    ("selected", "Selected"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                ],
                max_length=31,
                null=True,
            ),
        ),
    ]
