# Generated by Django 4.2.7 on 2025-11-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0003_job_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="logo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
