# Generated by Django 4.2.7 on 2025-11-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0004_job_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="salary_range",
        ),
        migrations.AddField(
            model_name="job",
            name="salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="job",
            name="logo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="skills",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="job",
            name="work_type",
            field=models.CharField(max_length=50),
        ),
    ]
