# Generated by Django 4.2.7 on 2025-12-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0005_jobprofile_candidatesearchlog_jobskill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidatesearchlog",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="candidatesearchlog",
            name="search_timestamp",
        ),
        migrations.RemoveField(
            model_name="candidatesearchlog",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="jobprofile",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="jobskill",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="jobskill",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="jobprofile",
            name="domain",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="jobprofile",
            name="highest_education",
            field=models.CharField(
                blank=True,
                choices=[
                    ("high_school", "High School"),
                    ("diploma", "Diploma"),
                    ("bachelor", "Bachelor's Degree"),
                    ("master", "Master's Degree"),
                    ("phd", "PhD"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
