# Generated by Django 4.2.7 on 2025-11-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0006_company_job_company_size_alter_job_salary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company_size",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
