const API_BASE =
  import.meta.env.BACKEND_API_BASE_URL || "http://127.0.0.1:8001/api";

// ------------------------------------------------------------
// Auth Header Helper
// ------------------------------------------------------------
function getAuthHeader(): Record<string, string> {
  const token = localStorage.getItem("token") || localStorage.getItem("access");
  if (token) {
    return { Authorization: `Bearer ${token}` };
  }
  return {};
}

function buildHeaders(extra?: Record<string, string>): HeadersInit {
  const auth = getAuthHeader();
  return { ...auth, ...(extra || {}) };
}


// ----------------------------------------
// TYPES (Match Backend Models & API)
// ----------------------------------------
export interface SocialLinks {
  id: string;
  github?: string | null;
  linkedin?: string | null;
  portfolio?: string | null;
  email?: string | null;
  website?: string | null;
}

export interface Skill {
  id: string;
  name: string;
  level: string; // beginner, intermediate, advanced
  percentage: number;
}

export interface Experience {
  id: string;
  company: string;
  role: string;
  duration: string;
  description_list: string[];
  technologies: string[];
}

export interface Project {
  id: string;
  title: string;
  description: string;
  role: string;
  tech_stack: string[];
  github_link?: string | null;
  live_link?: string | null;
}

export interface Education {
  id: string;
  institution: string;
  degree: string;
  field: string;
  duration: string;
  cgpa?: string | null;
  start_year?: number | null;
  end_year?: number | null;
}

export interface Certification {
  id: string;
  name: string;
  issuer: string;
  completion_date: string;
  certificate_file?: string | null;
}

export interface Profile {
  id: string;
  full_name: string | null;
  title: string | null;
  location: string | null;
  about: string | null;
  gender: string | null;
  profile_image?: string | null;
  cover_image?: string | null;
  google_id?: string | null;

  // Nested related fields
  links: SocialLinks;
  skills: Skill[];
  experiences: Experience[];
  projects: Project[];
  education: Education[];
  certifications: Certification[];

  created_at: string;
  updated_at: string;
}


// ----------------------------------------
// MAIN PROFILE REQUESTS
// ----------------------------------------

// Get full profile with nested data
export const fetchProfileDetail = async (): Promise<Profile> => {
  const res = await fetch(`${API_BASE}/auth/profile/detail/`, {
    headers: buildHeaders(),
  });

  if (!res.ok) throw new Error("Failed to fetch profile");
  return res.json();
};

// Update profile (full_name auto generated by backend)
export const updateProfileDetail = async (payload: any): Promise<Profile> => {
  const res = await fetch(`${API_BASE}/auth/profile/detail/`, {
    method: "PATCH",
    headers: buildHeaders({ "Content-Type": "application/json" }),
    body: JSON.stringify(payload),
  });

  if (!res.ok) throw new Error("Failed to update profile");
  return res.json();
};


// ----------------------------------------
// SOCIAL LINKS
// ----------------------------------------
export const updateSocialLinks = async (payload: Partial<SocialLinks>) => {
  // Remove empty strings (backend rejects them)
  const cleanedPayload = Object.fromEntries(
    Object.entries(payload).filter(([_, value]) => value && value.trim() !== "")
  );

  const res = await fetch(`${API_BASE}/auth/profile/links/`, {
    method: "PATCH",
    headers: buildHeaders({ "Content-Type": "application/json" }),
    body: JSON.stringify(cleanedPayload),
  });

  if (!res.ok) throw new Error("Failed to update social links");
  return res.json();
};


// ----------------------------------------
// SKILLS CRUD
// ----------------------------------------
export const addSkill = async (payload: Partial<Skill>) => {
  const res = await fetch(`${API_BASE}/auth/skills/add/`, {
    method: "POST",
    headers: buildHeaders({ "Content-Type": "application/json" }),
    body: JSON.stringify(payload),
  });

  if (!res.ok) throw new Error("Failed to add skill");
  return res.json();
};

export const updateSkill = async (id: string, payload: Partial<Skill>) => {
  const res = await fetch(`${API_BASE}/auth/skills/${id}/`, {
    method: "PATCH",
    headers: buildHeaders({ "Content-Type": "application/json" }),
    body: JSON.stringify(payload),
  });

  if (!res.ok) throw new Error("Failed to update skill");
  return res.json();
};

export const deleteSkill = async (id: string) => {
  const res = await fetch(`${API_BASE}/auth/skills/${id}/`, {
    method: "DELETE",
    headers: buildHeaders(),
  });

  if (!res.ok) throw new Error("Failed to delete skill");
  return true;
};


// ----------------------------------------
// EXPERIENCE CRUD
// ----------------------------------------
export const addExperience = async (payload: Partial<Experience>) => {
  const res = await fetch(`${API_BASE}/auth/experience/add/`, {
    method: "POST",
    headers: buildHeaders({ "Content-Type": "application/json" }),
    body: JSON.stringify(payload),
  });

  if (!res.ok) throw new Error("Failed to add experience");
  return res.json();
};

export const updateExperience = async (
  id: string,
  payload: Partial<Experience>
) => {
  const res = await fetch(`${API_BASE}/auth/experience/${id}/`, {
    method: "PATCH",
    headers: buildHeaders({ "Content-Type": "application/json" }),
    body: JSON.stringify(payload),
  });

  if (!res.ok) throw new Error("Failed to update experience");
  return res.json();
};

export const deleteExperience = async (id: string) => {
  const res = await fetch(`${API_BASE}/auth/experience/${id}/`, {
    method: "DELETE",
    headers: buildHeaders(),
  });

  if (!res.ok) throw new Error("Failed to delete experience");
  return true;
};


// ----------------------------------------
// PROJECT CRUD
// ----------------------------------------
export const addProject = async (payload: Partial<Project>) => {
  const res = await fetch(`${API_BASE}/auth/projects/add/`, {
    method: "POST",
    headers: buildHeaders({ "Content-Type": "application/json" }),
    body: JSON.stringify(payload),
  });

  if (!res.ok) throw new Error("Failed to add project");
  return res.json();
};

export const updateProject = async (id: string, payload: Partial<Project>) => {
  const res = await fetch(`${API_BASE}/auth/projects/${id}/`, {
    method: "PATCH",
    headers: buildHeaders({ "Content-Type": "application/json" }),
    body: JSON.stringify(payload),
  });

  if (!res.ok) throw new Error("Failed to update project");
  return res.json();
};

export const deleteProject = async (id: string) => {
  const res = await fetch(`${API_BASE}/auth/projects/${id}/`, {
    method: "DELETE",
    headers: buildHeaders(),
  });

  if (!res.ok) throw new Error("Failed to delete project");
  return true;
};


// ----------------------------------------
// EDUCATION CRUD
// ----------------------------------------
export const addEducation = async (payload: Partial<Education>) => {
  const res = await fetch(`${API_BASE}/auth/education/add/`, {
    method: "POST",
    headers: buildHeaders({ "Content-Type": "application/json" }),
    body: JSON.stringify(payload),
  });

  if (!res.ok) throw new Error("Failed to add education");
  return res.json();
};

export const updateEducation = async (
  id: string,
  payload: Partial<Education>
) => {
  const res = await fetch(`${API_BASE}/auth/education/${id}/`, {
    method: "PATCH",
    headers: buildHeaders({ "Content-Type": "application/json" }),
    body: JSON.stringify(payload),
  });

  if (!res.ok) throw new Error("Failed to update education");
  return res.json();
};

export const deleteEducation = async (id: string) => {
  const res = await fetch(`${API_BASE}/auth/education/${id}/`, {
    method: "DELETE",
    headers: buildHeaders(),
  });

  if (!res.ok) throw new Error("Failed to delete education");
  return true;
};


// ----------------------------------------
// CERTIFICATION CRUD
// ----------------------------------------
export const addCertification = async (
  payload: Partial<Certification>
) => {
  const res = await fetch(`${API_BASE}/auth/certification/add/`, {
    method: "POST",
    headers: buildHeaders({ "Content-Type": "application/json" }),
    body: JSON.stringify(payload),
  });

  if (!res.ok) throw new Error("Failed to add certification");
  return res.json();
};

export const updateCertification = async (
  id: string,
  payload: Partial<Certification>
) => {
  const res = await fetch(`${API_BASE}/auth/certification/${id}/`, {
    method: "PATCH",
    headers: buildHeaders({ "Content-Type": "application/json" }),
    body: JSON.stringify(payload),
  });

  if (!res.ok) throw new Error("Failed to update certification");
  return res.json();
};

export const deleteCertification = async (id: string) => {
  const res = await fetch(`${API_BASE}/auth/certification/${id}/`, {
    method: "DELETE",
    headers: buildHeaders(),
  });

  if (!res.ok) throw new Error("Failed to delete certification");
  return true;
};

// Update both User and Profile data
export async function updateProfile(data: EditProfileData) {
  // 1) Update user first_name, last_name
  const userRes = await fetch(`${API_BASE}/auth/profile/`, {
    method: "PATCH",
    headers: { ...getAuthHeader(), "Content-Type": "application/json" },
    body: JSON.stringify({
      first_name: data.first_name,
      last_name: data.last_name,
    }),
  });

  if (!userRes.ok) throw new Error("Failed to update user info");

  // 2) Update profile title, location, about
  const profileRes = await fetch(`${API_BASE}/auth/profile/detail/`, {
    method: "PATCH",
    headers: { ...getAuthHeader(), "Content-Type": "application/json" },
    body: JSON.stringify({
      title: data.title,
      location: data.location,
      about: data.about,
    }),
  });

  if (!profileRes.ok) throw new Error("Failed to update profile info");

  const updatedUser = await userRes.json();
  const updatedProfile = await profileRes.json();

  return {
    ...updatedProfile,
    first_name: updatedUser.first_name,
    last_name: updatedUser.last_name,
  };
}


// ----------------------------------------
// DEFAULT EXPORT
// ----------------------------------------
const profileService = {
  fetchProfileDetail,
  updateProfileDetail,
  updateProfile,

  updateSocialLinks,

  addSkill,
  updateSkill,
  deleteSkill,

  addExperience,
  updateExperience,
  deleteExperience,

  addProject,
  updateProject,
  deleteProject,

  addEducation,
  updateEducation,
  deleteEducation,

  addCertification,
  updateCertification,
  deleteCertification,
};

export default profileService;

